# Linear algebra in Python

Use the `numpy` and `scipy` libraries to handle our numerical operations.

In [25]:
import numpy as np # alias to "np"
from math import sqrt

## With vanilla Python:

In [27]:
# Vanilla Python way to use an array/vector:
a = [1, 3, 2]
b = [0, 2, 2]

def mult_bcast(a, b):
    return [i*j for (i,j) in zip(a,b)]

# do dot-product:
def dotProd(a, b):
    # BRACE YOURSELVES: Zip the arrays together and then iterate the pairs
    # zip(a,b)
    return sum(mult_bcast(a,b))

def sumSquares(a):
    return dotProd(a,a)

def lenth(a):
    return sqrt(sumSquares(a))

In [16]:
mult_bcast(a,b)

[0, 6, 4]

In [17]:
dotProd(a,b)

10

In [18]:
sumSquares(a)

14

In [28]:
lenth(a)

3.7416573867739413

## With Numpy

Documentation: [https://numpy.org/doc/stable/](https://numpy.org/doc/stable/).

Basics: `numpy.ndarray` is our primary array-like structure.
Create from a standard Python list by passing to the constructor: `np.array([1,2,3])`

In [45]:
a = np.array([1,3,2])
b = np.array([0, 2, 2])

In [46]:
a*b # broadcasts the multiplication

array([0, 6, 4])

In [47]:
# Dot-product: np.dot
print(np.dot(a,b))
# can also:
print(a.dot(b))
print(b.dot(a))

# query the "shape" of an array or matrix
print(a.shape)

10
10
10
(3,)


In [61]:
# use Matrices:
a = np.array([[1,3,2]]) # logically is now a bona-fide row-vector
b = np.array([[0,2,2]])
print(a)

# the .shape attribute returns a tuple where i'th entry is the number
# of indicies along that dimension/axis
# e.g. the 0'th axis is the rows, 1'th axis is the columns
print(a.shape)

[[1 3 2]]
(1, 3)


In [62]:
# We can easily transpose with the np.tranpose()
print(np.transpose(a)) # get a column-vector: shape is 3x1
print(np.transpose(a).shape)

[[1]
 [3]
 [2]]
(3, 1)


In [63]:
# Transpose sugar:
a.T

array([[1],
       [3],
       [2]])

In [64]:
a

array([[1, 3, 2]])

In [65]:
b

array([[0, 2, 2]])

In [66]:
a*b

array([[0, 6, 4]])

In [67]:
(a*b).sum() # numpy.array.sum() method


10

In [68]:
# in linear algebra, how to write row-vectors, x dot y algebraically (with matrix multiplication)
# matrix muliply: x * y.T
a * b.T # WRONG! broadcasted a "down" b

array([[0, 0, 0],
       [2, 6, 4],
       [2, 6, 4]])

In [69]:
a

array([[1, 3, 2]])

In [70]:
b

array([[0, 2, 2]])

In [71]:
b.T

array([[0],
       [2],
       [2]])

In [72]:
# Correct way to do matrix multiplication:
# Use the "@" operator
a @ b.T

array([[10]])

In [74]:
a @ b # NOPE

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [75]:
c = np.array([2,4,5])
d = np.array([1,1,2])

c @ d.T

16

In [76]:
d.T

array([1, 1, 2])

In [80]:
# generic 3-by-2
np.empty((3,2)) # takes a tuple of dimensions, DOES NOT initialize memory
# array of all 0's
np.zeros((3,2)) # initializes each element to 0

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [85]:
# Numpy does ranges! But they come in the form of an array
np.arange(3,40) # around the Python [i for i in range(3,40)], list(range(3,40))

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [92]:
np.arange(3,40,4)

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39])

In [94]:
np.array([np.arange(30,4,-4)])

array([[30, 26, 22, 18, 14, 10,  6]])

In [106]:
# numpy can "reshape" arrays!
# bonus example: random number:
a = np.random.randint(1,10,(2,6))
print(a)

[[1 7 1 9 3 2]
 [5 5 8 6 8 4]]


In [113]:
c = a.reshape((3,4)) # takes a tuple of the new dims
print(c)

[[1 7 1 9]
 [3 2 5 5]
 [8 6 8 4]]


In [114]:
# say we only want the 3-by-3 on the left of this matrix
c[0] # slice out the first row, returns a 1-d array

array([1, 7, 1, 9])

In [116]:
c[0:2] # provide a range to slice! Similar to pandas' DataFrame slicing

array([[1, 7, 1, 9],
       [3, 2, 5, 5]])

In [118]:
c[0][2]

1

In [117]:
c[0,2] # use special comma-separated indices

1

In [119]:
c[(0,2)] # also accepts tuples

1

In [120]:
c[0:2,0:2] # first two cols of first two rows

array([[1, 7],
       [3, 2]])

In [121]:
c[0:2,:] # all cols of first two rows

array([[1, 7, 1, 9],
       [3, 2, 5, 5]])

In [124]:
c[1:3,:] # last two rows, every col

array([[3, 2, 5, 5],
       [8, 6, 8, 4]])

In [125]:
c[1:3,...]

array([[3, 2, 5, 5],
       [8, 6, 8, 4]])

In [126]:
c[:,1:3] # every row, col 1 and 2

array([[7, 1],
       [2, 5],
       [6, 8]])

For more on indexing: [https://numpy.org/doc/stable/reference/arrays.indexing.html](https://numpy.org/doc/stable/reference/arrays.indexing.html).

In [127]:
c

array([[1, 7, 1, 9],
       [3, 2, 5, 5],
       [8, 6, 8, 4]])

In [128]:
a

array([[1, 7, 1, 9, 3, 2],
       [5, 5, 8, 6, 8, 4]])

In [129]:
a.shape

(2, 6)

In [130]:
c.shape

(3, 4)

In [131]:
3 in [1, 2, 3]

True

In [134]:
a =  {"1": 2, "3": 10, 15: "idontcare"}

In [135]:
a

{'1': 2, '3': 10, 15: 'idontcare'}

In [136]:
a['b'] = 'lkjsdf'

In [137]:
a

{'1': 2, '3': 10, 15: 'idontcare', 'b': 'lkjsdf'}

In [138]:
a[0]

KeyError: 0

In [139]:
[i for i in a]

['1', '3', 15, 'b']

In [140]:
a[(1,2)] = 'alex'

In [141]:
a

{'1': 2, '3': 10, 15: 'idontcare', 'b': 'lkjsdf', (1, 2): 'alex'}

In [142]:
[i for i in a]

['1', '3', 15, 'b', (1, 2)]

In [143]:
a['alex'] = (1,2)

In [144]:
a

{'1': 2,
 '3': 10,
 15: 'idontcare',
 'b': 'lkjsdf',
 (1, 2): 'alex',
 'alex': (1, 2)}