In [16]:
# Parker's Question: how to pass and a function in a subroutine

def callFunc(f, x):
    """ returns the value of f at x """
    return f(x)

def square(x):
    print("here")
    return x*x

In [17]:
callFunc(square, 10)

here


100

# Next Question...

In [18]:
square(10)

here


100

In [21]:
f = square

In [22]:
f(10)

here


100

In [23]:
callFunc(f,10)

here


100

In [8]:
type(square)

function

In [9]:
class Blah:
    def __init__(self):
        self.a = 10

In [10]:
b = Blah()

In [11]:
type(b)

__main__.Blah

# Tuples and sorting

In [26]:
arr = [(3, 'apple'), (5, 'orange'), (2, 'apple'), (1.4, 'apple'), (5.5, 'orange'), (10, 'apple')]

In [27]:
sorted(arr)

[(1.4, 'apple'),
 (2, 'apple'),
 (3, 'apple'),
 (5, 'orange'),
 (5.5, 'orange'),
 (10, 'apple')]

In [37]:
def firstPart(tup):
    print(f"firstPart({tup}) called")
    return tup[0] # just return first part

In [38]:
sorted(arr, key=firstPart)

firstPart((3, 'apple')) called
firstPart((5, 'orange')) called
firstPart((2, 'apple')) called
firstPart((1.4, 'apple')) called
firstPart((5.5, 'orange')) called
firstPart((10, 'apple')) called


[(1.4, 'apple'),
 (2, 'apple'),
 (3, 'apple'),
 (5, 'orange'),
 (5.5, 'orange'),
 (10, 'apple')]

In [36]:
sorted(arr, key=firstPart)[:3]

(3, 'apple')
(5, 'orange')
(2, 'apple')
(1.4, 'apple')
(5.5, 'orange')
(10, 'apple')


[(1.4, 'apple'), (2, 'apple'), (3, 'apple')]

In [39]:
sorted(arr)[:3]

[(1.4, 'apple'), (2, 'apple'), (3, 'apple')]

In [42]:
ary = [1,2,3,4,5,6]
name = 'apple'

#[(x,name) for x in ary]

res = []
for x in ary:
    res += [(x,name)]
    
res

[(1, 'apple'),
 (2, 'apple'),
 (3, 'apple'),
 (4, 'apple'),
 (5, 'apple'),
 (6, 'apple')]

In [51]:
import numpy as np
import numpy.linalg as la

test = np.array([[1,2,3,4]])
points = np.array([[1,5,3,2],[12,5,2,4],[2,5,4,2]])
la.norm(points-test,axis=1)
print(points-test)

[[ 0  3  0 -2]
 [11  3 -1  0]
 [ 1  3  1 -2]]


In [52]:
a = ["a", "b", "a"]
{l: 0 for l in a}

{'a': 0, 'b': 0}